[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Accessibility support"
  pageRef = "accessibility-specialist"
  weight = 20

[[main]]
  name = "Accessibility audit"
  pageRef = "audit-services"
  weight = 30

[[main]]
  name = "Systemic analyzer"
  pageRef = "analyzer"
  weight = 40

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "Accessibility support"
  pageRef = "accessibility-specialist"
  weight = 20

[[footer]]
  name = "Accessibility audit"
  pageRef = "audit-services"
  weight = 30

[[footer]]
  name = "Systemic analyzer"
  pageRef = "analyzer"
  weight = 40
