[[main]]
  name = "Bio"
  pageRef = "bio"
  weight = 10

[[main]]
  name = "Specialist support"
  pageRef = "accessibility-specialist"
  weight = 20

[[main]]
  name = "Accessibility audit"
  pageRef = "audit-services"
  weight = 30

[[main]]
  name = "Systemic analyzer"
  pageRef = "analyzer"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Bio"
  pageRef = "bio"
  weight = 10

[[footer]]
  name = "Specialist support"
  pageRef = "accessibility-specialist"
  weight = 20

[[footer]]
  name = "Accessibility audit"
  pageRef = "audit-services"
  weight = 30

[[footer]]
  name = "Systemic analyzer"
  pageRef = "analyzer"
  weight = 40

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 50
