baseURL = "https://example.com/"
languageCode = "en-gb"
title = "Accessibility Support"
theme = "blowfish"

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 12

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
