[goldmark]
  [goldmark.renderer]
    unsafe = true

[highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = false
  lineNumbersInTable = false
  tabWidth = 2

tableOfContents = { startLevel = 2, endLevel = 4, ordered = false }
