[[main]]
  name = "Support"
  pageRef = "accessibility-specialist"
  weight = 10

[[main]]
  name = "Audit"
  pageRef = "audit-services"
  weight = 20

[[main]]
  name = "Analyser"
  pageRef = "guides"
  weight = 30

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Support"
  pageRef = "accessibility-specialist"
  weight = 10

[[footer]]
  name = "Audit"
  pageRef = "audit-services"
  weight = 20

[[footer]]
  name = "Analyser"
  pageRef = "guides/accessibility-systemic-analyser"
  weight = 30
