[[main]]
  name = "Accessibility Specialist"
  pageRef = "accessibility-specialist"
  weight = 10

[[main]]
  name = "Accessibility Audit"
  pageRef = "audit-services"
  weight = 20

[[main]]
  name = "Analyzer Guides"
  pageRef = "guides"
  weight = 30

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Accessibility Specialist"
  pageRef = "accessibility-specialist"
  weight = 10

[[footer]]
  name = "Accessibility Audit"
  pageRef = "audit-services"
  weight = 20

[[footer]]
  name = "Accessibility Systemic Analyzer"
  pageRef = "guides/accessibility-systemic-analyzer"
  weight = 30

[[footer]]
  name = "Dashboard Guide"
  pageRef = "guides/dashboard-charts-and-metrics-guide"
  weight = 40

[[footer]]
  name = "Workbook Guide"
  pageRef = "guides/workbook-guide"
  weight = 50
