colorScheme = "accessible-clarity"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = false
enableCodeCopy = true
mainSections = ["analyzer", "testing", "accessibility", "conversational-ai"]

[homepage]
  layout = "profile"
  showRecent = false
  recentLimit = 6
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  sharingLinks = []
  showTags = false
  showCategories = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[footer]
  showCopyright = true
  showThemeAttribution = true

[header]
  layout = "fixed"
